import type { Discipline } from "./types";
import { LOW, LM, MH, HX, COOKED } from "./types";

// One entry per discipline. `match` is tested (in this order, first hit wins) against the
// lowercased "core" name of the major, then against the full name. Put the more specific
// disciplines before the broader ones.
//
// `pools` feed the {d.people}, {d.jobs}, {d.grind}, {d.tool} and {d.pain} tokens used by
// the "hybrid" templates. Keep every entry a plain phrase that reads fine in several sentences.
//
// `roasts` are complete, hand-written lines for that discipline. Leave `tiers` out for a line
// that works at any cooked level. Positive "you're fine" lines belong on LOW / LM only.

export const DISCIPLINES: Discipline[] = [  {
    id: "built",
    group: "stem",
    match: /architect|landscape|settlement|surveying|construction|interior|urban|town planning|land (economy|management)|real estate/,
    pools: {
      people: ["architecture students", "built-environment majors", "studio kids"],
      jobs: ["junior architects", "site engineers", "quantity surveyors"],
      grind: ["all-nighters in the studio", "gluing a model at 4am", "plotting drawings that never print right"],
      tool: ["AutoCAD", "Revit", "SketchUp"],
      pain: ["a 'quick' revision at 2am", "a model that collapsed before the crit", "a printer jam on deadline night"],
    },
    roasts: [
      { text: "studio taught you three things: coffee is a food group, sleep is a rumor, and the model is never fully glued." },
      { text: "{aiImg} made a render in 9 seconds. yours took 3 nights and a small breakdown.", tiers: MH },
      { text: "5 years designing buildings and the only space you can afford is a 'cozy studio'.", tiers: HX },
      { text: "your professor's feedback: 'interesting.' translation: start over." },
      { text: "the client wants it 'more modern, but also like a castle'. good luck." },
      { text: "you'll be fine. someone still has to say 'that won't hold' and be right.", tiers: LM },
    ],
  },
  {
    id: "accounting",
    group: "commerce",
    match: /accounting|actuarial|auditing|banking|financ|\btax/,
    pools: {
      people: ["accounting students", "finance majors", "future auditors"],
      jobs: ["junior accountants", "audit associates", "financial analysts"],
      grind: ["reconciling things that were never going to reconcile", "color-coding spreadsheets", "chasing a 3-cent difference"],
      tool: ["Excel", "QuickBooks", "SAP"],
      pain: ["a spreadsheet with 47 tabs", "a balance sheet that is off by 1 cent", "busy season"],
    },
    roasts: [
      { text: "Excel crashed with 40 tabs open and you still said 'it balances'. respect." },
      { text: "four years to become the person everyone ignores until tax season.", tiers: MH },
      { text: "{ai} can do the books. it can't look a manager in the eye and say 'that's not deductible'.", tiers: LM },
      { text: "the audit found nothing. the audit also found you haven't slept since January." },
      { text: "busy season isn't a season, it's a lifestyle with a deadline." },
      { text: "debits, credits, and somehow your social life is still in the red.", tiers: MH },
    ],
  },
  {
    id: "law",
    group: "people",
    match: /\blaw\b|\bllb\b|legal|jurispr/,
    pools: {
      people: ["law students", "future lawyers", "pre-law kids"],
      jobs: ["junior associates", "paralegals", "law clerks"],
      grind: ["reading 300 pages for a class that cold-calls you", "highlighting a case in 4 colors", "writing a brief at 3am"],
      tool: ["Westlaw", "a highlighter", "a 900-page casebook"],
      pain: ["a case brief due at 8am", "a cold call you didn't prepare for", "a 6-hour closed-book exam"],
    },
    roasts: [
      { text: "law school: 300 pages of reading to learn the answer is 'it depends'." },
      { text: "objection: you've been in the library for 14 hours and the bar exam hasn't even started." },
      { text: "{ai} summarized the case in 6 seconds. you billed 6 hours. the partner is thrilled.", tiers: MH },
      { text: "you'll be fine. somebody has to read the fine print {ai} confidently skipped.", tiers: LM },
      { text: "student debt, 80-hour weeks, and a firm that calls you 'family'. nice.", tiers: HX },
      { text: "the bar exam isn't a test, it's a trial, and you're the defendant.", tiers: MH },
    ],
  },
  {
    id: "medicine",
    group: "health",
    match: /medicine|dental|surgery|optometry|pharmac|veterinar|herbal|biomedical|doctor of/,
    pools: {
      people: ["med students", "future doctors", "pre-med kids"],
      jobs: ["junior doctors", "pharmacists", "house officers"],
      grind: ["memorizing 4,000 drug names", "a 28-hour shift", "pimping rounds with a dying phone"],
      tool: ["a stethoscope", "a coffee IV", "Anki"],
      pain: ["a 28-hour shift", "a patient who 'read about it online'", "a residency match"],
    },
    roasts: [
      { text: "11 years of school to hear a patient say 'i googled it and it's probably nothing'." },
      { text: "med school: where sleep is a theory and coffee is a prescribed medication." },
      { text: "{ai} can't do rounds, can't do night shifts and can't hold a patient's hand. you'll be fine.", tiers: LM },
      { text: "you studied for a decade to be told 'please hold' by an insurance company.", tiers: MH },
      { text: "residency match: a lottery you studied for 6 years.", tiers: MH },
      { text: "'the doctor will see you now' — the doctor, running on 2 hours of sleep and spite." },
    ],
  },
  {
    id: "health",
    group: "health",
    match: /nursing|midwifery|medical (imaging|laboratory)|physiotherap|rehabilitation|health|nutrition|dietet|radiograph|disability/,
    pools: {
      people: ["nursing students", "allied health students", "future nurses"],
      jobs: ["nurses", "lab technicians", "physiotherapists"],
      grind: ["12-hour shifts", "clinical placements that start at 6am", "charting at 3am"],
      tool: ["a pulse oximeter", "a very worn pair of clogs", "a clipboard"],
      pain: ["a double shift", "a placement with zero breaks", "a 14-hour day on your feet"],
    },
    roasts: [
      { text: "nursing school: 12-hour shifts, 4 hours of sleep, and a patient asking for 'the real doctor'." },
      { text: "{ai} can't start an IV, calm a panicking family, or survive nights. you're good.", tiers: LM },
      { text: "healthcare keeps the whole hospital running and pays in 'thank you for your service' energy.", tiers: MH },
      { text: "your feet hurt, your back hurts, and the group chat says 'at least it's stable'.", tiers: MH },
      { text: "you handle blood just fine. the job application portal is what makes you faint." },
      { text: "one day you'll say 'i'm fine' on hour 14 with a straight face. that's called character development." },
    ],
  },
  {
    id: "psychology",
    group: "people",
    match: /psycholog|counsel/,
    pools: {
      people: ["psych majors", "future therapists", "psychology students"],
      jobs: ["research assistants", "case managers", "HR coordinators"],
      grind: ["writing APA citations", "running a study with 6 participants", "analyzing your own feelings for credit"],
      tool: ["SPSS", "APA style", "a clipboard of consent forms"],
      pain: ["a study with 6 participants", "an APA formatting error", "a p-value of 0.051"],
    },
    roasts: [
      { text: "psych major: can analyze your feelings, can't analyze the job market." },
      { text: "everyone asks if you're reading their mind. you're reading the same 3 papers." },
      { text: "four years studying human behavior and still no explanation for 'entry-level, 3 years experience'.", tiers: MH },
      { text: "{ai} can mimic empathy. you can bill for it. for now.", tiers: LM },
      { text: "'what do you do with a psych degree?' 'grad school. then more grad school.'", tiers: MH },
      { text: "SPSS crashed and took your p-value with it. significant emotional damage." },
    ],
  },
  {
    id: "education",
    group: "people",
    match: /education|\bb\.?ed\b|teach|pedagog|early grade|specialism/,
    pools: {
      people: ["education majors", "future teachers", "teaching students"],
      jobs: ["teachers", "teaching assistants", "substitute teachers"],
      grind: ["writing lesson plans at midnight", "grading 80 essays", "practicum observations"],
      tool: ["a whiteboard marker", "a laminator", "a color-coded planner"],
      pain: ["a class of 50 and one projector", "a lesson plan nobody reads", "a Friday afternoon classroom"],
    },
    roasts: [
      { text: "teaching is saving the next generation, they said. 'buy your own supplies', they didn't say.", tiers: MH },
      { text: "your lesson plan took 6 hours. the kids asked 'is this on the test?'" },
      { text: "{ai} can write the lesson plan. it can't handle 40 kids on a Friday afternoon.", tiers: LM },
      { text: "teaching practicum: 8 weeks of 'you'll thank me later' from people who clearly haven't." },
      { text: "you'll shape minds. you'll also shape a whiteboard marker budget.", tiers: MH },
      { text: "wake up early, plan lessons, grade at midnight, repeat. 'passion' pays in vibes.", tiers: HX },
    ],
  },
  {
    id: "agriculture",
    group: "stem",
    match: /agricultur|agribusiness|aquaculture|forest|natural resources|dairy|meat|food science|post harvest|fisher|crop|animal|water resources|horticult/,
    pools: {
      people: ["agric students", "future farm managers", "agriculture majors"],
      jobs: ["agricultural officers", "farm managers", "extension officers"],
      grind: ["field practicals in the sun", "6am farm visits", "writing up a crop trial"],
      tool: ["a pair of wellington boots", "a soil probe", "a field notebook"],
      pain: ["a farm practical at 6am", "a drought during your project", "a lecture on the day the harvest was due"],
    },
    roasts: [
      { text: "agric major: studied crops for 4 years and the only thing growing is the stress.", tiers: MH },
      { text: "{ai} can't plant a tree. you can. that's the whole market advantage.", tiers: LM },
      { text: "farm practical at 6am, lecture at 8, sleep at never. that's the 'agri-culture'." },
      { text: "everyone says 'we need farmers' and then offers 'exposure' as a salary.", tiers: MH },
      { text: "your degree is 'a growing field'. so far, the only thing growing is the group chat." },
    ],
  },
  {
    id: "hospitality",
    group: "commerce",
    match: /tourism|hospitality|catering|hotel/,
    pools: {
      people: ["hospitality majors", "tourism students", "future hotel managers"],
      jobs: ["front desk agents", "hotel managers", "event coordinators"],
      grind: ["smiling at a guest yelling about a towel", "working a double banquet", "memorizing 12 types of wine"],
      tool: ["a name tag", "a very patient smile", "a radio headset"],
      pain: ["a guest who is 'always right'", "a double banquet", "a 3am fire alarm"],
    },
    roasts: [
      { text: "hospitality: you'll smile at someone yelling about a towel and still say 'have a great day'." },
      { text: "'the customer is always right' — said by customers, never by anyone who's worked a front desk." },
      { text: "{ai} can book a room. it can't fake a smile at 3am. that's your edge.", tiers: LM },
      { text: "4 years of learning service and the tip jar still says 'thank you' like it's a currency.", tiers: MH },
      { text: "tourism degree: seeing the world mostly through PowerPoint slides." },
    ],
  },
  {
    id: "creative",
    group: "arts",
    match: /design|ceramic|fashion|textile|painting|sculpture|\bart\b|fine art|\bbfa\b|graphic|illustrat|animation|photograph/,
    pools: {
      people: ["design students", "art majors", "creative kids"],
      jobs: ["junior designers", "illustrators", "freelance creatives"],
      grind: ["all-nighters before critique", "re-exporting at 3am", "explaining kerning to clients"],
      tool: ["Photoshop", "Figma", "Illustrator"],
      pain: ["a client who says 'make the logo bigger'", "a critique at 9am", "a file that crashed before saving"],
    },
    roasts: [
      { text: "'make the logo bigger.' (that's the entire feedback.)" },
      { text: "{aiImg} did a whole portfolio in a minute. the client still wants 'more pop'.", tiers: MH },
      { text: "design school: 4 years of learning kerning so you can hear 'just use Comic Sans'.", tiers: MH },
      { text: "your portfolio is gorgeous. your landlord only accepts money, sadly.", tiers: MH },
      { text: "freelance clients pay in exposure. you can't eat exposure, but your mom still asks about it.", tiers: HX },
      { text: "you'll be fine. a human still has to say 'this looks off' and be right.", tiers: LM },
    ],
  },
  {
    id: "cs",
    group: "stem",
    match: /comput|software|information|\bict\b|\bit\b|cyber|\bdata\b|database|informatics|artificial|machine learning|programming|\bweb\b|mobile|network/,
    pools: {
      people: ["CS majors", "future developers", "computing students"],
      jobs: ["junior developers", "software engineers", "IT support staff"],
      grind: ["debugging at 3am", "grinding LeetCode", "a group project where one guy writes everything"],
      tool: ["VS Code", "Stack Overflow", "GitHub"],
      pain: ["a merge conflict", "a null pointer exception", "'it works on my machine'"],
    },
    roasts: [
      { text: "your GitHub is 90% 'initial commit' and 10% a todo app. recruiters can see it.", tiers: MH },
      { text: "bro grinded 400 LeetCode problems for a job that asked him to center a div.", tiers: COOKED },
      { text: "tech layoffs looked at this degree and said 'we'll keep it on file'.", tiers: HX },
      { text: "{aiCode} writes the code, you write the commit message 'fixed stuff'. fair split.", tiers: MH },
      { text: "the only thing in CS that's actually safe is the Stack Overflow answer marked 'duplicate'." },
      { text: "you'll be fine. someone has to explain to {ai} what the client actually meant.", tiers: LM },
      { text: "CS major: 'i can fix anything.' also CS major: restarts the router for the whole family." },
      { text: "the internship rejection arrived in 4 minutes. automated. at 2am. they didn't even sleep on it.", tiers: MH },
    ],
  },
  {
    id: "engineering",
    group: "stem",
    match: /engineer|civil|mechanical|electrical|electronic|chemical|aerospace|automobile|materials|metallurgical|petrochemical|petroleum|geomatic|telecommunication|marine|mining|packaging|automotive/,
    pools: {
      people: ["engineering students", "future engineers", "engineering majors"],
      jobs: ["graduate engineers", "site engineers", "junior engineers"],
      grind: ["labs that start at 8am and end at never", "calculating the same thing 9 times", "a design project with 5 revisions"],
      tool: ["MATLAB", "AutoCAD", "Excel"],
      pain: ["a 40-page lab report", "a group project where the pump is never calibrated", "a simulation that crashed at 99%"],
    },
    roasts: [
      { text: "four years of calculus so a manager can say 'can we make it cheaper?' in the final meeting.", tiers: MH },
      { text: "engineers don't have bad days, they have 'unexpected load conditions'." },
      { text: "{ai} tried your thermodynamics homework and asked for a day off." },
      { text: "spent 4 years on tolerances and still can't tolerate the group project guy." },
      { text: "graduate engineer role. 5 years experience required. pays in 'exposure to real projects'.", tiers: HX },
      { text: "you'll be fine. bridges still need someone who says 'actually, that won't hold'.", tiers: LM },
      { text: "MATLAB crashed the night before the deadline. character development." },
    ],
  },
  {
    id: "math",
    group: "stem",
    match: /mathematic|statistic|\bmaths?\b/,
    pools: {
      people: ["math majors", "stats majors", "future actuaries"],
      jobs: ["data analysts", "quant interns", "teaching assistants"],
      grind: ["proofs that start with 'obviously'", "grinding problem sets till 2am", "typing LaTeX at midnight"],
      tool: ["LaTeX", "R", "a graphing calculator"],
      pain: ["a proof that only works on Tuesdays", "an exam with 4 questions and 3 hours", "a theorem left 'as an exercise'"],
    },
    roasts: [
      { text: "math major: sees the answer, writes 6 pages anyway because 'show your work'." },
      { text: "every problem is easy until the professor says 'it's left as an exercise to the reader'." },
      { text: "{ai} solved the integral. you're still stuck on 'let epsilon be greater than zero'.", tiers: MH },
      { text: "you can prove infinity exists. you can't prove you've got an interview.", tiers: MH },
      { text: "your job prospects are dividing by zero: undefined and slightly alarming.", tiers: HX },
      { text: "statistics says 93% of recruiters ignore you. the other 7% are bots.", tiers: HX },
    ],
  },
  {
    id: "science",
    group: "stem",
    match: /biolog|chemistry|biochem|physics|geolog|meteorolog|environmental|biotech|climate|science/,
    pools: {
      people: ["science majors", "lab rats", "future researchers"],
      jobs: ["lab technicians", "research assistants", "field scientists"],
      grind: ["writing 12-page lab reports", "pipetting at 7am", "waiting for a result that worked once"],
      tool: ["a pipette", "a fume hood", "Excel with 12 graphs"],
      pain: ["an experiment that worked once", "a lab partner who did nothing", "a 3am centrifuge"],
    },
    roasts: [
      { text: "science degree: 4 years making something work once, then 12 pages on why it won't again." },
      { text: "your lab partner did nothing. the results are therefore 'inconclusive'." },
      { text: "{ai} can summarize the paper. it can't pipette at 7am on shaky hands and a dream.", tiers: LM },
      { text: "'research assistant' is just 'unpaid intern' wearing a lab coat.", tiers: MH },
      { text: "your job market is a petri dish: grows slowly and smells weird.", tiers: MH },
      { text: "organic chemistry broke a lot of people. you survived. the job market is mild by comparison.", tiers: LOW },
    ],
  },
  {
    id: "economics",
    group: "commerce",
    match: /economic/,
    pools: {
      people: ["econ majors", "economics students", "future analysts"],
      jobs: ["junior analysts", "research associates", "policy analysts"],
      grind: ["drawing supply and demand curves", "defending a model with 14 assumptions", "running regressions at 2am"],
      tool: ["Excel", "Stata", "a very confident graph"],
      pain: ["a model with 14 assumptions", "an exam on 'shifts vs movements'", "a regression with nothing significant"],
    },
    roasts: [
      { text: "econ taught you that people are rational. then you met people." },
      { text: "ceteris paribus, you'd be employed. but nothing ever stays equal.", tiers: MH },
      { text: "your thesis predicts the market. the market did not read your thesis.", tiers: HX },
      { text: "{ai} drew the supply and demand curve in 3 seconds. you drew it for 3 semesters.", tiers: MH },
      { text: "econ major: can explain inflation, cannot explain rent." },
    ],
  },
  {
    id: "business",
    group: "commerce",
    match: /business|administration|management|market|entrepreneur|human resource|procurement|logistics|supply chain|commerce|retail|sales/,
    pools: {
      people: ["business majors", "future managers", "business students"],
      jobs: ["business analysts", "marketing assistants", "management trainees"],
      grind: ["group presentations", "networking events with free pizza", "building a deck with 40 slides"],
      tool: ["PowerPoint", "LinkedIn", "Excel"],
      pain: ["a 'networking event' with free pizza", "a pitch deck nobody asked for", "a group project with 'synergy'"],
    },
    roasts: [
      { text: "business major: 4 years, 11 group projects, 1 PowerPoint with 'synergy' on slide 3." },
      { text: "everyone in your degree is a 'founder' on LinkedIn. nobody is founding anything.", tiers: MH },
      { text: "{ai} wrote your pitch deck. the investor asked who you are and you said 'a visionary'.", tiers: MH },
      { text: "your network is strong. your income is 'in progress'.", tiers: LM },
      { text: "you'll be fine. someone has to schedule the meeting about the meeting.", tiers: LM },
      { text: "'entrepreneur' in the bio, 'unemployed' in the bank account, 'disrupting' in the group chat.", tiers: HX },
    ],
  },
  {
    id: "media",
    group: "arts",
    match: /communicat|journalis|media|publishing|broadcast|film|public relations|advertis/,
    pools: {
      people: ["comms majors", "journalism students", "media kids"],
      jobs: ["content creators", "copywriters", "social media managers"],
      grind: ["writing 800 words on deadline", "posting three times a day", "re-editing a caption for the 9th time"],
      tool: ["Canva", "a ring light", "a content calendar"],
      pain: ["a press release nobody reads", "a headline that was 'too long'", "a deadline that was 'yesterday'"],
    },
    roasts: [
      { text: "journalism degree: trained to chase the truth, hired to chase 'engagement'.", tiers: MH },
      { text: "{ai} wrote the article, the headline, and the clickbait follow-up. you watched.", tiers: HX },
      { text: "comms major: 4 years of writing, still can't write 'looking for work' without 'passionate'.", tiers: MH },
      { text: "your personal brand is 'storyteller' and 3 followers who are all family." },
      { text: "you'll be fine. someone has to fact-check the confident nonsense {ai} just wrote.", tiers: LM },
      { text: "'content creator' is just 'unemployed with a ring light'. a photogenic start though.", tiers: MH },
    ],
  },
  {
    id: "humanities",
    group: "arts",
    match: /english|french|history|religio|philosoph|language|linguist|literature|theolog|classic|culture|\barts?\b/,
    pools: {
      people: ["humanities majors", "English majors", "history kids"],
      jobs: ["writers", "editors", "research assistants"],
      grind: ["reading a 500-page book overnight", "writing an essay on 'what does it all mean?'", "annotating the same 3 pages"],
      tool: ["a highlighter", "a library card", "a very worn paperback"],
      pain: ["an essay on 'what does it all mean?'", "a 9am seminar on a book you skimmed", "a thesis statement at 2am"],
    },
    roasts: [
      { text: "english major: knows 40 words for 'sad', still can't write a cover letter that doesn't read like a poem.", tiers: MH },
      { text: "history major: knows exactly how this ends. the economy, the job market, all of it.", tiers: HX },
      { text: "{ai} can write essays. it can't look a professor in the eye and say 'it's about the human condition'.", tiers: LM },
      { text: "'what are you going to do with that?' — everyone at every family gathering, forever." },
      { text: "philosophy degree: you can argue anything, including that you're employed." },
      { text: "your degree taught you to think critically. now think critically about the rent.", tiers: MH },
    ],
  },
  {
    id: "social",
    group: "people",
    match: /sociolog|political|\bsocial\b|geograph|develop|anthropolog|international relations|criminolog|rural|planning/,
    pools: {
      people: ["social science majors", "poli sci kids", "development studies students"],
      jobs: ["policy interns", "program officers", "research assistants"],
      grind: ["writing a 3,000-word essay on 'power structures'", "field work with a clipboard", "citing 40 sources at 2am"],
      tool: ["a survey form", "a field notebook", "a very long reading list"],
      pain: ["a field study in the rain", "a survey nobody answered", "a seminar on 'systems'"],
    },
    roasts: [
      { text: "sociology major: can explain exactly why you're broke, can't fix it.", tiers: HX },
      { text: "poli sci: you've debated the entire government. the government hasn't hired you.", tiers: MH },
      { text: "{ai} summarized the theory. you lived the 'field work' with a clipboard and nobody answered." },
      { text: "social work: you'll save the world and the world will say 'hold on, budget cuts'.", tiers: MH },
      { text: "4 years studying society to discover society doesn't have an opening for you yet.", tiers: HX },
      { text: "you'll be fine. somebody has to understand what people actually want, not what {ai} predicts.", tiers: LM },
    ],
  },
];

