// SERVER ONLY. The downloadable PDF of the unlocked report, drawn from the same Plan object as the web
// version (see lib/plan/generate.ts), so the two always match. Dark, editorial, peach and orange accents,
// the site's typefaces, and a footer with the page number on every page.

import { Document, Font, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import { PLAN_COPY } from "@/lib/premium";
import type { Plan } from "@/lib/plan/types";
import { geist400, geist700, geist900, mono700 } from "./fonts-data";

Font.register({
  family: "Geist",
  fonts: [
    { src: geist400, fontWeight: 400 },
    { src: geist700, fontWeight: 700 },
    { src: geist900, fontWeight: 900 },
  ],
});
Font.register({ family: "GeistMono", src: mono700, fontWeight: 700 });
// Keep words whole: the default hyphenation splits words in odd places
Font.registerHyphenationCallback((word) => [word]);

const C = {
  bg: "#111111",
  card: "#191919",
  border: "#2c2c2c",
  text: "#eeeeee",
  body: "#cfcfcf",
  muted: "#9a9a9a",
  peach: "#ffe0c2",
  orange: "#f97316",
  red: "#e54d2e",
  green: "#10b981",
};

const s = StyleSheet.create({
  page: { backgroundColor: C.bg, color: C.text, fontFamily: "Geist", fontSize: 10, paddingTop: 54, paddingBottom: 70, paddingHorizontal: 48 },
  mono: { fontFamily: "GeistMono", fontWeight: 700, letterSpacing: 1.6, textTransform: "uppercase" },
  h1: { fontWeight: 900, textTransform: "uppercase", letterSpacing: -1, lineHeight: 1 },
  h2: { fontWeight: 900, fontSize: 24, textTransform: "uppercase", letterSpacing: -0.6, lineHeight: 1.05, color: C.text },
  h3: { fontWeight: 700, fontSize: 10.5, lineHeight: 1.3, textTransform: "uppercase", color: C.text, letterSpacing: 0.2 },
  p: { color: C.body, fontSize: 10, lineHeight: 1.6 },
  card: { backgroundColor: C.card, borderWidth: 1, borderColor: C.border, borderRadius: 10, padding: 12, marginBottom: 8 },
});

const levelColor = (score: number) => (score > 80 ? C.red : score > 40 ? C.orange : C.green);

function scoreFormat(n: number) {
  return `${n}%`;
}

/** Heading block at the top of each content page. */
function PageHead({ n, title, kicker }: { n: string; title: string; kicker?: string }) {
  return (
    <View style={{ marginBottom: 18 }} fixed={false}>
      <Text style={[s.mono, { fontSize: 8, color: C.peach }]}>{`${n}  /  ${kicker ?? "Major Intelligence"}`}</Text>
      <Text style={[s.h2, { marginTop: 6 }]}>{title}</Text>
      <View style={{ width: 44, height: 3, backgroundColor: C.orange, marginTop: 10 }} />
    </View>
  );
}

function Label({ children, color = C.muted }: { children: string; color?: string }) {
  return <Text style={[s.mono, { fontSize: 7.5, color, marginBottom: 6 }]}>{children}</Text>;
}

function Item({ title, why }: { title: string; why?: string }) {
  return (
    <View style={s.card} wrap={false}>
      <Text style={s.h3}>{title}</Text>
      {why ? <Text style={[s.p, { marginTop: 3 }]}>{why}</Text> : null}
    </View>
  );
}

function Bullets({ items, color = C.orange }: { items: string[]; color?: string }) {
  return (
    <View>
      {items.map((t) => (
        <View key={t} style={{ flexDirection: "row", marginBottom: 6 }} wrap={false}>
          <View style={{ width: 5, height: 5, borderRadius: 3, backgroundColor: color, marginTop: 5, marginRight: 9 }} />
          <Text style={[s.p, { flex: 1 }]}>{t}</Text>
        </View>
      ))}
    </View>
  );
}

function Stat({ label, value, color = C.text }: { label: string; value: string; color?: string }) {
  return (
    <View style={{ flex: 1, backgroundColor: C.card, borderWidth: 1, borderColor: C.border, borderRadius: 10, padding: 10 }}>
      <Text style={[s.mono, { fontSize: 6.5, color: C.muted }]}>{label}</Text>
      <Text style={{ fontWeight: 900, fontSize: 13, color, marginTop: 4, lineHeight: 1.2 }}>{value}</Text>
    </View>
  );
}

// Fixed elements sit directly under the Page. Do not set lineHeight on the footer texts or on the Page:
// the renderer drops a render-function text (the page number) when a lineHeight applies to it.
function Footer() {
  return (
    <>
      <View fixed style={{ position: "absolute", bottom: 44, left: 48, right: 48, height: 1, backgroundColor: C.border }} />
      <Text fixed style={{ position: "absolute", bottom: 28, left: 48, fontFamily: "GeistMono", fontWeight: 700, fontSize: 7, color: C.muted, letterSpacing: 1.4 }}>
        GENERATED BY MAJORLABS INTELLIGENCE
      </Text>
      <Text
        fixed
        style={{ position: "absolute", bottom: 28, right: 48, width: 120, textAlign: "right", fontFamily: "GeistMono", fontWeight: 700, fontSize: 7, color: C.peach, letterSpacing: 1.4 }}
        render={({ pageNumber, totalPages }) => `${String(pageNumber).padStart(2, "0")} / ${String(totalPages).padStart(2, "0")}`}
      />
    </>
  );
}

/** Wording for the "watch out" sections. Safe majors never get negative language. */
const VULNERABLE_TITLE = { uncooking: "Paths to move away from", future_proof: "Paths to watch", advantage: "Areas to watch" } as const;
const DEPRIORITISE_NOTE = {
  uncooking: "Do not build your next two years on these. Use them only as stepping stones toward the roles above.",
  future_proof: "Keep a foot in these if you must, but do not let them be your only story.",
  advantage: "These parts of the field will change fastest. Stay curious about them and keep your edge sharp.",
} as const;

export function PlanPdf({ plan }: { plan: Plan }) {
  const copy = PLAN_COPY[plan.planType];
  const color = levelColor(plan.major.score);
  const nameSize = plan.major.name.length > 46 ? 30 : plan.major.name.length > 30 ? 38 : 48;
  const topOpp = plan.strongPaths.slice(0, 2).map((p) => p.title);

  return (
    <Document title={`${plan.planName} - ${plan.major.name}`} author="MajorLabs Intelligence" subject="Major Intelligence Career Plan, 2026 Edition" creator="MajorLabs Intelligence">
      {/* 1. Cover */}
      <Page size="A4" style={s.page}>
        <View style={{ flexDirection: "row", justifyContent: "space-between" }}>
          <Text style={[s.mono, { fontSize: 8, color: C.peach }]}>MajorLabs Intelligence</Text>
          <Text style={[s.mono, { fontSize: 8, color: C.muted }]}>2026 Edition</Text>
        </View>

        <View style={{ flex: 1, justifyContent: "center" }}>
          <Text style={[s.mono, { fontSize: 9, color: C.orange }]}>{copy.eyebrow}</Text>
          <Text style={[s.h1, { fontSize: nameSize, marginTop: 14, color: C.text }]}>{plan.major.name}</Text>
          <View style={{ width: 64, height: 5, backgroundColor: C.peach, marginTop: 18 }} />

          <View style={{ flexDirection: "row", alignItems: "flex-end", marginTop: 42 }}>
            <Text style={{ fontWeight: 900, fontSize: 112, lineHeight: 0.9, letterSpacing: -4, color }}>{scoreFormat(plan.major.score)}</Text>
            <View style={{ marginLeft: 22, marginBottom: 10 }}>
              <Text style={[s.mono, { fontSize: 7.5, color: C.muted }]}>Cooked score</Text>
              <Text style={{ fontWeight: 900, fontSize: 20, textTransform: "uppercase", color, marginTop: 4 }}>{plan.major.level}</Text>
            </View>
          </View>

          <View style={{ marginTop: 44, borderTopWidth: 1, borderTopColor: C.border, paddingTop: 16 }}>
            <Text style={[s.mono, { fontSize: 7.5, color: C.muted }]}>Your plan</Text>
            <Text style={{ fontWeight: 900, fontSize: 22, lineHeight: 1.15, textTransform: "uppercase", color: C.peach, marginTop: 5, marginBottom: 6 }}>{plan.planName}</Text>
            <Text style={[s.p, { marginTop: 6, maxWidth: 380 }]}>{copy.headline}</Text>
          </View>
        </View>
        <Footer />
      </Page>

      {/* 2. The Verdict */}
      <Page size="A4" style={s.page}>
        <PageHead n="01" title="The Verdict" />
        <View style={{ flexDirection: "row", gap: 8, marginBottom: 18 }}>
          <Stat label="Cooked score" value={scoreFormat(plan.major.score)} color={color} />
          <Stat label="Level" value={plan.major.level} color={color} />
          <Stat label="Typical pay" value={plan.major.salary} />
          <Stat label="Market growth" value={plan.major.growth} color={plan.major.growth.includes("-") ? C.red : C.green} />
        </View>
        <Label color={C.peach}>Overview</Label>
        <Text style={[s.p, { fontSize: 11.5, color: C.text, lineHeight: 1.6, marginBottom: 18 }]}>{plan.overview}</Text>
        <Label color={C.peach}>Why you got this score</Label>
        <Text style={s.p}>{plan.whyScore}</Text>
        <Footer />
      </Page>

      {/* 3. AI & Job Market */}
      <Page size="A4" style={s.page}>
        <PageHead n="02" title="AI & Job Market" />
        <View style={[s.card, { borderColor: color, marginBottom: 18 }]} wrap={false}>
          <Text style={[s.mono, { fontSize: 7.5, color }]}>{`AI exposure: ${plan.aiExposure.label}`}</Text>
          <Text style={[s.p, { marginTop: 5 }]}>{plan.aiExposure.summary}</Text>
        </View>
        <View style={{ flexDirection: "row", gap: 16, marginBottom: 18 }}>
          <View style={{ flex: 1 }}>
            <Label color={C.orange}>AI already does well</Label>
            <Bullets items={plan.aiExposure.atRisk} color={C.orange} />
          </View>
          <View style={{ flex: 1 }}>
            <Label color={C.green}>Stays human</Label>
            <Bullets items={plan.aiExposure.staysHuman} color={C.green} />
          </View>
        </View>
        <Label color={C.peach}>Career outlook</Label>
        <Text style={s.p}>{plan.outlook}</Text>
        <Footer />
      </Page>

      {/* 4. Your Opportunities */}
      <Page size="A4" style={s.page}>
        <PageHead n="03" title="Your Opportunities" />
        <Label color={C.green}>Strong career paths</Label>
        {plan.strongPaths.map((p) => (
          <Item key={p.title} title={p.title} why={p.why} />
        ))}
        <View style={{ marginTop: 14 }}>
          <Label color={C.orange}>{VULNERABLE_TITLE[plan.planType]}</Label>
          {plan.vulnerablePaths.map((p) => (
            <Item key={p.title} title={p.title} why={p.why} />
          ))}
        </View>
        <Footer />
      </Page>

      {/* 5. Skills to Stack + AI tools */}
      <Page size="A4" style={s.page}>
        <PageHead n="04" title="Skills to Stack" />
        {plan.skills.map((p) => (
          <Item key={p.title} title={p.title} why={p.why} />
        ))}
        <View style={{ marginTop: 16 }} minPresenceAhead={80}>
          <Text style={[s.mono, { fontSize: 8, color: C.peach }]}>AI tools to learn</Text>
          <Text style={[s.h2, { fontSize: 18, marginTop: 5, marginBottom: 10 }]}>Your AI toolkit</Text>
          {plan.aiTools.map((p) => (
            <Item key={p.title} title={p.title} why={p.why} />
          ))}
        </View>
        <Footer />
      </Page>

      {/* 6. Projects */}
      <Page size="A4" style={s.page}>
        <PageHead n="05" title="Projects to Build" />
        <Text style={[s.p, { marginBottom: 14 }]}>Proof beats claims. These are the pieces that make an employer believe you.</Text>
        {plan.projects.map((p, i) => (
          <View key={p.title} style={[s.card, { flexDirection: "row" }]} wrap={false}>
            <Text style={{ fontWeight: 900, fontSize: 22, color: C.orange, width: 34, lineHeight: 1 }}>{String(i + 1).padStart(2, "0")}</Text>
            <View style={{ flex: 1 }}>
              <Text style={s.h3}>{p.title}</Text>
              <Text style={[s.p, { marginTop: 3 }]}>{p.why}</Text>
            </View>
          </View>
        ))}
        <Footer />
      </Page>

      {/* 7. Roadmap */}
      <Page size="A4" style={s.page}>
        <PageHead n="06" title="30 / 60 / 90 Day Roadmap" />
        {plan.roadmap.map((phase) => (
          <View key={phase.days} style={[s.card, { padding: 14, marginBottom: 12 }]} wrap={false}>
            <View style={{ flexDirection: "row", alignItems: "flex-end", marginBottom: 8 }}>
              <Text style={{ fontWeight: 900, fontSize: 34, color: C.peach, lineHeight: 0.9 }}>{phase.days}</Text>
              <View style={{ marginLeft: 10 }}>
                <Text style={[s.mono, { fontSize: 7, color: C.muted }]}>days</Text>
                <Text style={{ fontWeight: 900, fontSize: 11, textTransform: "uppercase", color: C.text }}>{phase.theme}</Text>
              </View>
            </View>
            {phase.steps.map((step, i) => (
              <View key={step} style={{ flexDirection: "row", marginBottom: 5 }}>
                <Text style={[s.mono, { fontSize: 8, color: C.orange, width: 20, marginTop: 1 }]}>{String(i + 1).padStart(2, "0")}</Text>
                <Text style={[s.p, { flex: 1 }]}>{step}</Text>
              </View>
            ))}
          </View>
        ))}
        <Footer />
      </Page>

      {/* 8. Strategy */}
      <Page size="A4" style={s.page}>
        <PageHead n="07" title="Strategy" />
        <Label color={C.green}>What to prioritise</Label>
        <Bullets items={plan.positioning} color={C.green} />
        <View style={{ marginTop: 10 }}>
          <Label color={C.peach}>Internship and job strategy</Label>
          <Bullets items={plan.internship} color={C.peach} />
        </View>
        <View style={{ marginTop: 10 }}>
          <Label color={C.peach}>How to become more employable</Label>
          <Bullets items={plan.employability} color={C.peach} />
        </View>
        <View style={{ marginTop: 10 }} minPresenceAhead={70}>
          <Label color={C.orange}>{plan.planType === "advantage" ? "Where to be selective" : "What to avoid"}</Label>
          <Text style={[s.p, { marginBottom: 6 }]}>{DEPRIORITISE_NOTE[plan.planType]}</Text>
          <Bullets items={plan.vulnerablePaths.map((p) => p.title)} color={C.orange} />
        </View>
        <Footer />
      </Page>

      {/* 9. Final Verdict */}
      <Page size="A4" style={s.page}>
        <PageHead n="08" title="Final Verdict" />
        <Text style={[s.p, { fontSize: 12.5, color: C.text, lineHeight: 1.65, marginBottom: 22 }]}>{plan.conclusion}</Text>
        <View style={[s.card, { borderColor: C.peach, padding: 16 }]} wrap={false}>
          <Text style={[s.mono, { fontSize: 7.5, color: C.peach }]}>Your first move</Text>
          <Text style={{ fontWeight: 900, fontSize: 15, textTransform: "uppercase", color: C.text, marginTop: 5 }}>Start the 30-day list this week</Text>
          <Text style={[s.p, { marginTop: 6 }]}>
            {topOpp.length ? `Aim at ${topOpp.join(" and ")}. ` : ""}
            Re-scan your major in six months to see how the picture changes.
          </Text>
        </View>
        <View style={{ marginTop: 28 }}>
          <Text style={[s.mono, { fontSize: 7, color: C.muted }]}>how-cooked-is-your-major.vercel.app</Text>
          <Text style={[s.p, { fontSize: 8.5, color: C.muted, marginTop: 6 }]}>
            This report is general guidance based on the typical shape of the field. It is not a promise about any job or salary. Your choices matter more than any score.
          </Text>
        </View>
        <Footer />
      </Page>
    </Document>
  );
}
